name: FIAT-GUI
dependencies:
  - python >=3.10
  - gdal
  - pip
  - dash
  - pip:
      - dash-bootstrap-components
      - git+https://github.com/Deltares/Delft-FIAT.git
      - toml
      - waitress
      - visdcc
